### ISSUE TITLE
Supporting POS as a non-embedded app

### ISSUE THREAD

**Issue by kartikluke** [Shopify/shopify_app#1023]
Hey we are non-embedded app but we're running into issues with running on POS. It seems like we have to be embedded to run on POS.

Is it possible for the app to be embedded just for POS but be non-embedded otherwise. This would help generally solve the problem.

However if the above is not easy to do maybe we can try and solve it by handling the specific issue we're running into. When the POS tries to load webapp we get stuck at the login page but trying to login fails because of an invalid authenticity token. I believe most of this is handled by embedded apps.

Shopify support says that POS should work with non-embedded apps so I was wondering if I'm doing something wrong.

**Comment by paulomarg** [comment]
> Is it possible for the app to be embedded just for POS but be non-embedded otherwise. This would help generally solve the problem.

Yes, that is possible and it is up to the App.

> When the POS tries to load webapp we get stuck at the login page but trying to login fails because of an invalid authenticity token

There may be an issue on the App side here. Did you check that you are getting a proper token for the login? You might need to update some cookie settings to be able to perform it. You can check this page out for more information: https://shopify.dev/tutorials/migrate-your-app-to-support-samesite-cookies

**Comment by kartikluke** [comment]
@paulomarg I tried enabling same-site cookies using `config.enable_same_site_none = true` but I'm still seeing the same issue. I'm not sure about how to check if I'm getting a proper token.

To my other question. How could I set up the app to be embedded only for Shopify POS.

**Comment by kartikluke** [comment]
**On Android:**

With `config.embedded_app = false`
![Screenshot_2020-06-25-12-31-27-900_com shopify pos](https://user-images.githubusercontent.com/3857139/85676586-5e5a5b00-b6e4-11ea-8023-8cac3e1f8b39.jpg)

With `config.embedded_app = true`
![Screenshot_2020-06-25-12-56-28-415_com shopify pos](https://user-images.githubusercontent.com/3857139/85676382-2e12bc80-b6e4-11ea-8f31-c2530b78739b.jpg)

**Comment by paulomarg** [comment]
So, the ERR_BLOCKED_BY_RESPONSE error you're seeing in Android is because your app is not embedded, so it refuses to be inserted in an iframe (for example, in Chrome you would see the error `Refused to display '...' in a frame because it set 'X-Frame-Options' to 'sameorigin'`). You can get more information on that header here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options.

That HTTP header is only set when you set `config.embedded_app = false`, so that's why it would work when `embedded = true`.

You can probably get this to work by keeping your app's `config.embedded_app = false`, but configuring your app to be embedded on POS only. To do that, go to your partner dashboard, in your app settings, you can go into the **Extensions** section and set the **Embedded App** options as disabled for admin and enabled for POS.

That will trigger your app to load in the POS and fail because of **X-Frame-Options**. You can unset this header for example by running `response.headers.except!('X-Frame-Options')` after your action - Rails sets it to `SAMEORIGIN` by default as per https://guides.rubyonrails.org/v6.0/security.html and that prevents your app from being loaded by POS.

Hope this helps!

**Comment by paulomarg** [comment]
Closing this issue as there doesn't seem to be a backend bug in play, and the problem can be solved as per above.
