### ISSUE TITLE
How to disable cookie sessions?

### ISSUE THREAD

**Issue by netwire88** [Shopify/shopify_app#1071]
We are trying to migrate to JWT (so far it's a bit buggy and documentation is sparse). We figured out how to resolve some issues but still have a few key questions.

- How do I know if JWT is actually working? We see the `Authorization Bearer` in the header, but it seems that the cookie is still being used? I dug into `LoginProtection` and noticed this, does that mean if a cookie exists, it'll still use that? 
```
    def shop_session
      shop_session_by_jwt || shop_session_by_cookie
    end
```
- Also, how's is the Authorization being checked?
- Do I need to implement `SessionRepositor.retrieve_by_shopify_domain` similar to `SessionRepository.retrieve(id)`?

**Comment by NabeelAhsen** [comment]
To be certain that JWT-based authentication is working, you can [turn off third-party cookies](https://support.google.com/chrome/answer/95647?co=GENIE.Platform%3DDesktop&hl=en) in your browser and then observe the behaviour. 

Your app's `shop_session` will prefer to validate a session using your JWT rather than a cookie. A cookie is now checked only if your app doesn't have `ShopifyApp.configuration.allow_jwt_authentication` set to `true` and your browser allows third-party cookies to be read and written to.

The Shopify App gem offers a JWT middleware that validates your token and session:
- https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/session/jwt.rb
- https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/middleware/jwt_middleware.rb

You shouldn't need to implement a new `SessionRepository` method if you determine that your app is using App Bridge authentication successfully.

**Comment by theundeadmonk** [comment]
Hey @netwire88 to add on to what Nabeel mentioned,

1) The cookie is only used as a fallback. i.e. in case your app frontend didn't send a JWT as a header.

2) The authorization is being checked in the middleware. https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/session/jwt.rb#L41
Since the header is a JWT, the middleware verifies that it was signed with the app's shared secret.

3) You do not need to implement `SessionRepository.retrieve_by_shopify_domain`. You have the Shopify domain available to you via the `jwt_shopify_domain` method and you can just call `ShopifyApp::SessionRepository.retrieve_shop_session_by_shopify_domain(jwt_shopify_domain)`

**Comment by NabeelAhsen** [comment]
> We are trying to migrate to JWT (so far it's a bit buggy and documentation is sparse).

Also, would you mind sharing here what you found buggy about the new JWT auth?

**Comment by netwire88** [comment]
Thank you @thedrummeraki and @NabeelAhsen, this is very good info. I started digging into the app (which uses Turbolinks) but am getting some very odd behaviors using different browsers. 

The app is based on the [Shopify Turbolinks JWT example](https://github.com/Shopify/turbolinks-jwt-sample-app). The unauthenticated uses `SplashPageController` and implements:
```
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop
```

Scenario: Go to an already installed app from Shopify Admin > Apps > app

Chrome Incognito (with "Block third-party cookies in Incognito" enabled)
1. Go to the app from the store > Apps
2. App loads, but seems to be using cookies? See [screenshot](https://www.screencast.com/t/on1jKkT2s0d).

Safari Private Window
1. Go to the app from the store > Apps
2. The app oddly again prompts [Requests login "Enter your shop domain to log in or install this app."](https://www.screencast.com/t/NLkCTcyEXU)
3. I get `ActionController::InvalidAuthenticityToken` error, see [screenshot 1](https://www.screencast.com/t/6imnawrP1IFz) and [screenshot 2](https://www.screencast.com/t/RtwbRhtS2)

**Comment by NabeelAhsen** [comment]
@netwire88 Thank you for the extra info.

Regarding Issue 1, I think those cookies in your screenshot are first-party cookies. The domain they're saved from is `*.shopify.com`, which is expected and normal. Third-party cookies should not be saved however, whose domains match your app's domain.

**Comment by NabeelAhsen** [comment]
I think the Safari issue might be related to the observation that the `Authorization` header isn't being set on requests as intended. 

Info needed: Is your `data-remote=true` set on form submits, and if so, are you using `$form.submit()`?

**Comment by netwire88** [comment]
Hi @NabeelAhsen , 
Regarding the link question, this isn't for forms, just simple a href. See example:

```
<a class="dropdown-item waves-effect waves-light mdi mdi-video" role="button" data-remote="true" href="/help">
            Help
</a>
```

**Comment by netwire88** [comment]
Hi @NabeelAhsen ,
Regarding issue #1, are you seeing similar issues with Safari?

**Comment by theundeadmonk** [comment]
Hi @netwire88 just to clarify, are you seeing the `ActionController::InvalidAuthenticityToken` on your splash screen? If so you need to disable CSRF protection there. 

On an authenticated page, the only time you will see `ActionController::InvalidAuthenticityToken` is if the jwt recieved was invalid.

Can you confirm that the Authorization header is being set.

**Comment by netwire88** [comment]
> Hi @netwire88 just to clarify, are you seeing the `ActionController::InvalidAuthenticityToken` on your splash screen? If so you need to disable CSRF protection there.
> 
> On an authenticated page, the only time you will see `ActionController::InvalidAuthenticityToken` is if the jwt recieved was invalid.
> 
> Can you confirm that the Authorization header is being set.

I also tried `protect_from_forgery except: :index` for `SplashPageController` and that didn't work either.

Here's the flow in Safari Private Window (it's the same in Safari), see [screencast](https://www.screencast.com/t/qboaXLF7bkD9)

1. Go to SplashPageController from Shopify admin > Apps > app
2. Tries to render the view, which has the `shopify_app.js`
3. I get redirected to standard Shopify login again. 

After I enter the login, I get the `ActionController::InvalidAuthenticityToken` error, but there seems to be an `authenticity_token`, see [screencast](https://www.screencast.com/t/oOaly4wbMes)

**Comment by NabeelAhsen** [comment]
Hey @netwire88, I don't think there is a need to use `data-remote="true"` because Turbolinks ensures that every request your app makes is an Ajax request. Furthermore, setting the `data-remote="true"` will override the event handlers that you have defined in `shopify_app.js`, and it will not send a session token to your app backend via the `Authorization` header.

Also please ensure that you have all of the functions defined in the [Authenticate server-side rendered apps with session tokens using App Bridge and Turbolinks](https://shopify.dev/tutorials/authenticate-server-side-rendered-apps-with-session-tokens-app-bridge-turbolinks#fetch-and-store-session-tokens) guide within your `shopify_app.js`.

A possible reason why your `SplashPageController` might be redirecting to your app's login page is that your app is not capturing the `shop` parameter correctly. See the following: https://github.com/Shopify/shopify_app/blob/4fa5baf42cb7867befc8a5dc610d688a5c6745d9/app/controllers/concerns/shopify_app/require_known_shop.rb#L19-L21

**Comment by netwire88** [comment]
> Hey @netwire88, I don't think there is a need to use `data-remote="true"` because Turbolinks ensures that every request your app makes is an Ajax request. Furthermore, setting the `data-remote="true"` will override the event handlers that you have defined in `shopify_app.js`, and it will not send a session token to your app backend via the `Authorization` header.
> 
> Also please ensure that you have all of the functions defined in the [Authenticate server-side rendered apps with session tokens using App Bridge and Turbolinks](https://shopify.dev/tutorials/authenticate-server-side-rendered-apps-with-session-tokens-app-bridge-turbolinks#fetch-and-store-session-tokens) guide within your `shopify_app.js`.
> 
> A possible reason why your `SplashPageController` might be redirecting to your app's login page is that your app is not capturing the `shop` parameter correctly. See the following:
> 
> https://github.com/Shopify/shopify_app/blob/4fa5baf42cb7867befc8a5dc610d688a5c6745d9/app/controllers/concerns/shopify_app/require_known_shop.rb#L19-L21

Thanks, I'll take a look at RequireKnownShop. As for `remote=true`, unfortunately UJS is required for many functionalities within the app. Is there an event handler such as `document.addEventListener("turbolinks:request-start"` that I can override to help with this?

**Comment by netwire88** [comment]
> 
> A possible reason why your `SplashPageController` might be redirecting to your app's login page is that your app is not capturing the `shop` parameter correctly. See the following:
> 
> https://github.com/Shopify/shopify_app/blob/4fa5baf42cb7867befc8a5dc610d688a5c6745d9/app/controllers/concerns/shopify_app/require_known_shop.rb#L19-L21

Thanks, I debugged this further and found that if you go to a direct link such as `/home`, the app goes into an redirect infinite loop.

I tried this set up and it didn't work. `check_shop_domain` isn't called.
```
class SplashPageController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::RequireKnownShop

class HomeController < AuthenticatedController

class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
```

I also tried changing `AuthenticatedController`:
```
class AuthenticatedController < ApplicationController
  include ShopifyApp::Authenticated
  include ShopifyApp::RequireKnownShop
```

But`shopify_app.js` runs `Turbolinks.visit(data.loadPath);` without a `shop` parameter, also creating an infinite loops and fails.

**Comment by netwire88** [comment]
@NabeelAhsen Any update on this? Especially with deep linking? For example, for https://github.com/Shopify/turbolinks-jwt-sample-app/, if you deep link to `/products`, does it work?
