### ISSUE TITLE
How to implement a whitelist of shops?

### ISSUE THREAD

**Issue by jamiemtdwyer** [Shopify/shopify_app#1076]
Hey all,

I'm working on a project for a client, and the goal is to have the Shopify app hidden from the public internet. I want to add protections against the index route and `/login` route to validate:
* the presence of the `shop` parameter
* that the `shop` parameter is contained within some hard-coded whitelist

Is this something that anyone has experience with, or has a general idea of how to accomplish? Is this achievable without monkey patching `shopify_app`? If monkey patching is required, is it generally known what the approach would be here?

Appreciate the assist.

**Comment by jamiemtdwyer** [comment]
Once I get a good grasp on how to accomplish this, I'm happy to open a PR to add this functionality if it's desired.

**Comment by paulomarg** [comment]
To add this sort of custom behaviour to the standard `shopify_app` actions, you could try one of these:
* Add a [Rack middleware](https://guides.rubyonrails.org/rails_on_rack.html#action-dispatcher-middleware-stack) that validates the parameters you want to check. If the params are not valid, you can return an error HTTP response (e.g. a `404 Not Found`)
* Inherit the controller that defines the actions you want to hide, add a `before_filter` to it that verifies the parameters, and override the `index` and `login` routes to go there instead

The middleware is probably the cleaner approach, but both should solve your issue.

Since this functionality is somewhat specific to your scenario and it can be done using standard Rails tools, I think it would be better placed in your app rather than the gem.

Hope this helps!

**Comment by jamiemtdwyer** [comment]
Thanks @paulomarg, appreciate it! you can go ahead and close this :+1:

**Comment by paulomarg** [comment]
Thanks, and happy coding!
