### ISSUE TITLE
Oauth error invalid_request: The redirect_uri is not whitelisted (Need help with redirect_uri when configuring Azure Frontdoor for shopify application in azure)

### ISSUE THREAD

**Issue by karthique** [Shopify/shopify_app#1080]
My application runs in azure environment. -> URL: abc.dev.azurewebsites.net

I have created an azure front door for the application -> URL: xyz.dev.fd.azure.net

**Flow:**
Shopify <--> Azure Front Door (xyz.dev.fd.azure.net) <--> Azure Server(abc.dev.azurewebsites.net)

When creating the app i have provided the app url and redirection url as front door url.
App URL: https://xyz.dev.fd.azure.net/
Redirection url: https://xyz.dev.fd.azure.net/auth/callback

When I perform the app installation I am being shown: "Oauth error invalid_request: The redirect_uri is not whitelisted"

The URL still takes the server url (abc.dev.azurewebsites.net) throwing the redirect_uri is not whitelisted (URL given below)

https://teststore.myshopify.com/admin/oauth/authorize?state=XXX&scope=read_products%2C%20read_orders...2F%2Fabc.dev.azurewebsites.net%2Fauth%2Fcallback&grant_options%5B%5D=per-user

How do i make the change to point to the front door url?

**Comment by tanema** [comment]
Well you are trying to redirect to `abc.dev.azurewebsites.net` but you have configured your APIClient with a redirect URL of `https://xyz.dev.fd.azure.net/auth/callback` so you have not whitelisted the appropriate URL.

ShopifyApp and our omniauth provider are not setup to redirect users to another domain and we cannot support this because it would be too custom. If want to redirect to a separate domain during your callback phase then you will need to remove ShopifyApp and omniauth-shopify-oauth2 and write your own authorization flow because both are setup entirely to authenticate with the application running it.

I do not know what azure frontdoor is, what are you trying to accomplish with this?

**Comment by karthique** [comment]
Front door is kind of a load balancer and it provides a separate url through which the application can be reached.
I have configured the front door url at apps end and whitelisted it as well.

The issue comes when i perform an install app, the OAuth takes the server url (abc.dev.azurewebsites.net) instead of front door url (xyz.dev.fd.azure.net). Because there is a URL mismatch between the one configured in shopify and one received it throws the error.

Sample below:
https://teststore.myshopify.com/admin/oauth/authorize?state=XXX&scope=read_products%2C%20read_orders...2F%2Fabc.dev.azurewebsites.net%2Fauth%2Fcallback&grant_options%5B%5D=per-user

**Comment by paulomarg** [comment]
Hi @karthique! I think @tanema is right, but there might be a workaround (untested).

The redirect URL is actually created by the OmniAuth gem - it uses the host name of the server running the code. In a load-balanced scenario, you'd want to set it up so that it redirects back to the LB rather than the server that processed the previous request.

You could use the [`.configure`](https://www.rubydoc.info/github/intridea/omniauth/OmniAuth.configure) method from OmniAuth to set the `full_host` value, that is what ends up being the root of the URL in our `redirect_uri` param.

For instance, you could add this to the omniauth initializer:

```ruby
OmniAuth.configure { |config| config.full_host = '<LB URL>' }
```

I can't say whether changing this will have any unexpected side effects, but it might be worth trying out.
