### ISSUE TITLE
Rails 6 and Trying to Not Use Sprockets

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1105]
I use Webpack for assets. However, when sending the production code to Heroku it complains:

    You set your `config.assets.compile = true` in production.

Which, I did not do, as that is not even a config method at this time. I think this is due to Sprockets. But if I remove Sprockets by commenting it out of the application.rb, the current install of Shopify fails as it believes it needs assets from Sprockets? 

What is the easy way to eliminate sprockets, just use Webpack, and have my cake and eat it too?

**Comment by paulomarg** [comment]
Hi @resistorsoftware! Currently, this value doesn't seem to be set by the default `shopify_app` app - I created one with the Shopify CLI (which basically runs `rails new; rails generate shopify_app`) and deployed it with the CLI `deploy` command, that works as expected.

Apparently, that check fails based on this command in Heroku:
```
rails runner "begin; puts %Q{heroku.detecting.config.for.assets.compile=#{Rails.application.config.try(:assets).try(:compile)}}; rescue => e; puts e; puts e.backtrace; end;"
```

As per https://github.com/heroku/heroku-buildpack-ruby/issues/879, you could try running that in your Heroku console to see if it is indeed set. You can also run the same check locally in a production environment to see if it's enabled:
```
RAILS_ENV=production rails runner "begin; puts %Q{heroku.detecting.config.for.assets.compile=#{Rails.application.config.try(:assets).try(:compile)}}; rescue => e; puts e; puts e.backtrace; end;"
```

One possibility that comes to mind is that a gem used by your app is setting the value, so you could maybe check the gems you've added since bootstrapping your app to see if they're the ones making the change.

**Comment by resistorsoftware** [comment]
If I leave Sprockets in the App, and just not use it, keep it empty, I can set config.assets.compile to false. Only when I turn off Sprockets does the App bitch about not knowing what config.assets are... so I am assuming they are a sprockets thing. Hence my question. For now, I just leave Sprockets in the Rails App and I just don't use it... clunky but it works.

**Comment by itsniper** [comment]
Sprockets is used in `shopify_app` for a few assets here:
https://github.com/Shopify/shopify_app/blob/740d6cd0bb60cc8ea65347049ac3de47a23a4c8a/lib/shopify_app/engine.rb#L17

I haven't figured out an easy way to switch those to Webpack, so I guess I'll do the same and leave Sprockets just for this 🤷‍♂️ .

**Comment by resistorsoftware** [comment]
The interesting thing is, those assets are almost all concerned with the hoisting of the authentication info INTO the iframe after the login, whereas with the JWT approach, that is not needed. So it would be interesting to turn off Sprockets, not have those assets, and thus be free of it. But, as always, that is an oversimplification I guess and there are other gotchas.
