### ISSUE TITLE
How to Re-Install App?

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1150]
Rails 6.0.3.4, Shopify App 17.0.1

I installed the App using the Merchant Store link generator for my localhost App. The Shopify App has a bug, so it bugged out at the Webhooks install method. [#1128](https://github.com/Shopify/shopify_app/issues/1128)

I decided to delete the App from the merchant store. I then inserted some debug code in the Shopify App code, and then tried to re-install the App, but it refuses to re-install now. What? What are we supposed to do in these cases? No error in the console. But clearly something is now messed up. Sigh... help? Nothing in my added puts code should be causing this. I am merely trying to see where Shopify App blows up internally.

<img width="551" alt="Shopify_Plus" src="https://user-images.githubusercontent.com/123307/105077412-7d428500-5a5a-11eb-8f04-fa4567651251.png">

Note that even when I remove the 1 puts statement in the Shopify App gem, the App still refuses to work? What is the problem here? Why is this happening? What does it mean "There is no Page at this address"?

**Comment by rezaansyed** [comment]
Hi @resistorsoftware,

It seems that the issue is that your app assumes it is installed because `shopify_app` checks for the existence of the shop record. The way to fix this is to mark the shop record as uninstalled on an `app/uninstalled` webhook. We updated the docs around this and recommend you check this out: https://shopify.dev/tutorials/mark-a-shop-record-as-uninstalled-using-webhooks#define-a-background-job

We also have this represented in our [sample app](https://github.com/Shopify/turbolinks-jwt-sample-app#marking-shops-as-uninstalled-on-appuninstalled-webhook)

**Comment by resistorsoftware** [comment]
Ya, I saw that. But what makes me laugh is that your explanation only works theoretically. By that I mean that the following is true ... ====>

I have the app/uninstalled webhook as part of all my apps. But since the latest changes to the Shopify App gem code now bork and blow chunks when installing in a shop, one can have a Shop installed, but webhooks are never installed due to this bug, so we do not get the desired automatic Shop removal from the DB. 

So I will now manually remove the shop from my DB, say my Homer Simpson "DOH", and hope that soon enough this bug in the App gem gets fixed, so that THIS ISSUE in particular, does not bite me again. 

Thanks!
