### ISSUE TITLE
Using graphiql  with AuthenticatedController

### ISSUE THREAD

**Issue by RobsonKing** [Shopify/shopify_app#1171]
I am using graphql gem and the graphiql-rails gem

I have made my graphql controller an AuthenticatedController to handle security and setup the session so that I can use ShopifyAPI::GraphQL.client.

This works great, but I would also like to use graphiql to test my queries in the development environment.  But this doesn't work without a valid auth token.

grahiql does provide a way of setting the auth header via an initializer

/config/initializers/graphiql.rb

`GraphiQL::Rails.config.headers['Authorization'] = -> (context) { "Bearer *****"}`

So I am wondering is there someway that I can create a new session for the first shop (for testing it doesn't mater)

`ShopifyAPI::Session.new(domain: Shop.first.shopify_domain, token:
Shop.first.shopify_token, api_version: "2021-01")` 

Is there someway I can get the token I need to pass to the Authorization header from this?

**Comment by thecodepixi** [comment]
Hey there @RobsonKing! 👋  

If I'm understanding your question correctly, you might have some issues trying to access the GraphiQL page on your app in this way, since apps need to be embedded on Shopify to have access to that session token to pass to the authorization header. What might help you is [our own GraphiQL App](https://shopify-graphiql-app.shopifycloud.com/login), which you can embed on your test store and run queries through. 

If that doesn't help, or I've misunderstood the issue, please let me know and I'll see what else I can do to help.

**Comment by RobsonKing** [comment]
I have used your graphiql app, which is excellent. 

But I want to connect to my graphql backend, so I want to see my schema in graphiql.  Which is protected by

`class GraphqlController < AuthenticatedController`

 which includes ShopifyApp::Authenticated

but it sounds like there is no way to bypass this.
