### ISSUE TITLE
"fullpage_redirect_to" is not working

### ISSUE THREAD

**Issue by udaantech** [Shopify/shopify_app#1287]
### Description
I have added this gem (version 18.0) and using turbolinks to make it multipage app with session token. I have done it successfully.
Now, i am facing issue when add recurring application charge. I have created charge successfully and getting response. 
In response, I am getting confirmation url and i am trying to redirect it using "fullpage_redirect_to" but it is not redirecting to cofirmation url.
Please help me.
Thanks in advance.

**Comment by asecondwill** [comment]
I'm doing this in the Pay View
Controller.
 @url = charge.confirmation_url

View
<%= javascript_tag do %>
  window.top.location.href = "<%= @url %>"; 
<% end %>

**Comment by udaantech** [comment]
> <%= javascript_tag do %>
> window.top.location.href = "<%= @url %>";
> <% end %>

If i have tried your solution but now seeing app install screen in iframe.

**Comment by asecondwill** [comment]
Can you show me the value of @url or how you created the charge?

**Comment by khoimm92** [comment]
Are you include *ShopifyApp::ShopAccessScopesVerification* in the controller? If so, I think I got the cause. It will not redirect to confirmation page because the shop param is not present. Check this function in *shopify_app-17.2.1/app/controllers/concerns/shopify_app/shop_access_scopes_verification.rb*
```
def current_shopify_domain
    return if params[:shop].blank?
    ShopifyApp::Utils.sanitize_shop_domain(params[:shop])
end
```
So my advice, move all the charge function to another controller, that not include *ShopAccessScopesVerification*

**Comment by yourivdlans** [comment]
What I think that is happening here (correct me if I'm wrong) is that the `fullpage_redirect_to` method renders the view `shopify_app/shared/redirect` which includes `redirect.js`. But due to the way Turbolinks works this is not picked up.

When inspecting my network calls I can see the request returning the proper output but this is not used. It seems this method is not compatible with turbolinks.

I tried to get the `shopify_app/shared/redirect` view working with something like the [turbolinks_render](https://github.com/jorgemanrubia/turbolinks_render) gem but hit a dead end because `redirect.js` was not loaded which would ensure the redirect would be performed.

So in the end I wrote a new redirect method which uses some js code from `redirect.js`.

Added this to my `AuthenticatedController`
```rb
def top_redirect_to(url)
  script = <<-SCRIPT
    (function(){
      normalizedLink = document.createElement('a');
      normalizedLink.href = "#{url}";

      data = JSON.stringify({
        message: 'Shopify.API.remoteRedirect',
        data: {location: normalizedLink.href}
      });
      window.parent.postMessage(data, "https://#{current_shopify_domain}");
    })();
  SCRIPT
  self.status = 200
  self.response_body = script
  response.content_type = "text/javascript"
end
```

Now when creating a charge I can redirect the user like so:
```rb
class SubscriptionsController < AuthenticatedController
  def update
    ...
    top_redirect_to result.data.app_subscription_create.confirmation_url
  end
end
```

**Comment by yourivdlans** [comment]
@forsbergplustwo Nice one! Thanks for sharing :)

**Comment by jackculpan** [comment]
This has saved me after many hours of searching. Thnak you so much! @forsbergplustwo

**Comment by meshane** [comment]
Me too. Thanks @forsbergplustwo
