### ISSUE TITLE
What is this line of code for? 

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1334]
From this file: https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/script-tags.md

    {event:'onload', src: ->(domain) { dynamic_tag_url(domain) } }

What is domain parameter? Where does that even come from? What is this method dynamic_tag_url?

**Comment by resistorsoftware** [comment]
Woe. The sheer number of stale issues these bots are closing is wild. No one bothered to help out and answer this one either...

**Comment by epair** [comment]
That line is explaining how to dynamically configure script-tags per shop based on the shop's domain (typically `*.myshopify.com`). I have something like this in our `config/initializers/shopify_app.rb`:

```ruby
config.scripttags = [
  {event: 'onload', src: ->(domain) { "https://#{host}/shopify/#{domain}.js" } },
]
```

So the domain param is the `shop_domain` and I assume that the `dynamic_tag_url` method in that file is an example of using a method for declaring the url instead of explicitly defining it. [Here's the code that implements using a proc for script-tag definitions.](https://github.com/Shopify/shopify_app/blob/946850333c5da7a681beb3a4dc71cdd99e932f22/lib/shopify_app/managers/scripttags_manager.rb#L16-L24) Hope that helps.
