### ISSUE TITLE
Log4J Java library vulnerability

### ISSUE THREAD

**Issue by dianedouglas-thrive** [Shopify/shopify_app#1337]
Hello Shopify Engineers! 
I was just notified by Shopify that there is an important security vulnerability in the Log4J Java library. 

My app is built with the shopify_app rails engine and I'm not aware of using the Log4J library anywhere - I have not added any extra gems. But I wanted to see if this rails engine uses it anywhere.

Is there any action that needs to be taken to update to the latest version of this gem? Do you use anything with Log4J? 

Thanks so much, just wanted to be sure.

**Comment by resistorsoftware** [comment]
It's a problem with people using Apache webserver. Nothing in this gem using Apache or links to Apache, or even remotely uses Java, although there is jRuby, and perhaps people playing in that ecosystem may have to think about it a little more.

**Comment by dianedouglas-thrive** [comment]
Sounds good, thanks!

**Comment by resistorsoftware** [comment]
Note that the reason everyone is terrified of this vulnerability is the fact that script kiddies using it are just bombing it at IPs. If it finds it's way into a system, and then finds itself in some code you are using but not writing, that payload can explode in there, and cause the damage too. So it is not just attacking one thing, this nasty little creature seeks out vulnerable software inside systems, using logs, till the logs get executed by this bug. 

So while Shopify App is seemingly benign, you may be using other code that is a problem, so be careful! 

Once the script kiddies get their fill and the skilled attacks start to happen, we'll see a lot of problems Internet-wide due to this bug.
