### ISSUE TITLE
Can't uninstall and reinstall the app with App Bridge 2.0

### ISSUE THREAD

**Issue by sagar-ranglani** [Shopify/shopify_app#1369]
### Steps to Reproduce

1. Generate a sample rails app
2. Install the app once, the session does not exist => Installation successful
3. Uninstall the app (Shop stays in the db)
4. Install the app again from the partner dashboard; All apps > App Name > Test your app > Select Store > Select same store as this does not provide :host params
5. App installation not successful

**Expected behavior:**

App Re-Installattion should be successful.

**Actual behavior:**

App Re-Installattion is NOT successful. The error in the browser console: `APP::ERROR::INVALID_CONFIG: host must be provided` since the installation link from The partners dashboard does not contain `host` param and shopify_app does not redirect to login as the shop session (in the db) still exists

**Reproduces how often:**

Every time reinstallation of the app is done on same shop

### Browsers

Chrome 

### Gem versions

18.1.1

### Security

- [x] I have redacted any private information from my logs or code snippets.

**Comment by hannachen** [comment]
👋 Hi Sagar, thanks for reporting this issue. Out of box, the app does not handle cleanup tasks when an app is uninstalled such as removing the shop entry. The reason for that is because the task might look different for each app, but it's recommended that your app subscribe to the `app/uninstall` webhook topic upon successful installation to avoid issues like this.

More information: https://github.com/Shopify/shopify_app/blob/master/docs/Troubleshooting.md#my-app-wont-install

**Comment by tiimgreen** [comment]
Also having issues reinstalling my app, it's getting rejected every time because this issue. Any updates on this?

**Comment by awd** [comment]
Hey @hannachen + @paulomarg - we are asking for some help - can you bring in others on your team to assist? The gem has a very long list of bugs - and I am sure many of us would help but there isn't much direction here and the internal forces pushing this gem are unknown to us on the outside.

How is per-user grants and oauth handled in this gem now that it is `19.x`? What is the expectation?
