### ISSUE TITLE
Script Tags Still Not working

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#1384]
I am still curious why no one has answered this. This repository has a section on Scripttags and it just does not compute. 

    config.scripttags = [
      {event: "onload", src: "https://example.com/fancy.js"},
      {event: "onload", src: ->(domain) { dynamic_tag_url(domain) }}
    ]

First off. There is no helper dynamic_tag_url anywhere I can find. Secondly, even if we remove that errant line, the other src comes back with with a routing error problem. The resource cannot be found. 

Anyone care to chime in and explain how they are dishing out script tags with this App 18.1.1

**Comment by vfonic** [comment]
Hey David,

Both of these are supposed to be _examples_. They are not working code. The first one shows how you can specify the ScriptTag as a string. The second example shows how you can dynamically generate the url, instead of passing it as a string.

Instead of `"https://example.com/fancy.js"`, you'd put your own Rails app url. For example: `"https://my-cool-app.com/main-script-tag-that-loads-all-the-code-and-sets-up-the-theme.js"`

In the second example you could use a Rails router helper such as: `posts_script_tag_asset(domain)` or `asset_path('posts_script_tag.js')` (note that you need to get the full URL here, so do some testing in Rails console for example)

**Comment by resistorsoftware** [comment]
While I agree, they are just examples, it is poor practice to put in deceptive examples that appear to be real. It would've taken the original author a little effort to make a more realistic example. and to define the use of the lamda with some explanation, as you did. Indeed I got my code to work despite this poor example, but it does rankle when you run into these situations where less than optimal care was taken with documenting how to use what is an important aspect of a serious project, involving many people.
