### ISSUE TITLE
Upgrade path 5.x to 6.x

### ISSUE THREAD

**Issue by pjc** [Shopify/shopify_app#141]
Hi,

We tried to update the shopify_app gem that our embedded app relies on, because we need bootstrap 3 for an html editor gem we want to use.

However, based on the error messages we get it seems like the entire configuration of the app is different between 5.x and 6.x versions of the shopify_app gem.

Is there a changelog available somewhere we can use as upgrade guidelines? Or should we create a new app with the latest 6.x gem and compare ourselves?

I want to be careful before messing with the basic config of my app.

**Comment by kevinhughes27** [comment]
Here is the changelog although its not super complete: https://github.com/Shopify/shopify_app/blob/master/CHANGELOG

It highlights the main changes to the app but one thing it doesn't mention is that we removed Bootstrap from this gem. This doesn't mean you can't use it it just means you'll need to re-add it to your gemfile in your project. The other changes shouldn't affect your app unless you use the new concerns otherwise the previously generated code will still be the same.
