### ISSUE TITLE
Need to implement pagination in Ruby on Rails when fetching orders from Shopify using API

### ISSUE THREAD

**Issue by raakesh11** [Shopify/shopify_app#1761]
## Below code to implement pagination is not working while fetching new orders from Shopify.

`LIMIT=250`
`def fetch_shopify_orders(status="paid")
    ShopifyAPI::Order.all(session: @session, financial_status: status, updated_at_min: Time.current.to_date - 2.days, limit: LIMIT)
  end`

`def fetch_next_shopify_orders
    ShopifyAPI::Order.all(session: @session, page_info: ShopifyAPI::Order.next_page_info, limit: LIMIT)
  end`

`orders = fetch_shopify_orders
  while ShopifyAPI::Order.next_page?
    orders = fetch_next_shopify_orders
  end`

I have taken reference from here https://shopify.github.io/shopify-api-ruby/usage/rest.html.

Using configuration mentioned below.
ruby '2.6.10'
gem 'rails',                      '~> 5.1.6'
gem 'shopify_api',                '~> 12.5.0'

Please help me to resolve this issue, any help would be highly appreciated.

**Comment by silvolu** [comment]
Hi,

If I understand correctly you are asking how to correctly use the pagination feature in your code, rather then reporting an issue with the feature itself. If that's the case, could you please post the question to our [developer forums](https://community.shopify.com/c/shopify-cli-and-tools/bd-p/tools)?
If that's not the case, but make sure to fill all the info that the template asks for so that we can try to reproduce the issue.
