### ISSUE TITLE
22.2.0 update and HomeController

### ISSUE THREAD

**Issue by flavio-b** [Shopify/shopify_app#1842]
@zzooeeyy, first of all, thanks for your work on `22.2.0`.

I have some questions in regard to this update and the use of `HomeController`.  Our Home controller is the default that comes when you run `shopify_app`'s generators:

```ruby
class HomeController < ApplicationController
  include ShopifyApp::EmbeddedApp
  include ShopifyApp::EnsureInstalled
  include ShopifyApp::ShopAccessScopesVerification

  def index
    if ShopifyAPI::Context.embedded? && (!params[:embedded].present? || params[:embedded] != "1")
      redirect_to(ShopifyAPI::Auth.embedded_app_url(params[:host]) + request.path, allow_other_host: true)
    else
      @shop_origin = current_shopify_domain
      @host = params[:host]
    end
  end
end
``` 

Is this still necessary given the `22.2.0` update?

**Comment by zzooeeyy** [comment]
Hey @flavio-b, it really depends on how your app's install flow is set up -- 

The HomeController is still important because it includes the `EnsureInstalled` concern. These are necessary to handle cases someone is trying to access your home URL outside of the Shopify admin iFrame.. 

Shopify AppBridge injects the important parameters about the current session that's loaded to your app's URL when it's loaded in the iframe including the host, session token, the shop it's loaded in etc. So if your app's home URL is opened without being inside Shopify admin, this controller will detect that it doesn't contain the necessary information (missing params from URL) to load the Shopify session and redirects the user to the app's login page so that they could input their shop and redirect them to admin to embed the app..

So if your app doesn't depend on this workflow and only works inside Shopify admin's iframe, then it _shouuulld_ work with just the `AuthenticatedController`.. But I can't say for sure since every app is different..
