### ISSUE TITLE
Authentication as admin?

### ISSUE THREAD

**Issue by heldopslippers** [Shopify/shopify_app#208]
Hi Guys, 

I have been breaking my head over this. Is there a way to authenticate as an admin. 
We have an admin page where we can see all the shops. 

I would like to have some kind of switch which enables us to see the app as the client sees it, so we can help them or check if there are any problems. 

Have tried to set just the shopify_domain but that doesn't really work. 
Anybody have a solution?

**Comment by kevinhughes27** [comment]
Are you using the Embedded App SDK? The issue you are going to run into here is that even though the merchant has installed your app you don't have access to their Shopify account so you won't be able to load the app the same way they can. You are going to need to build an entire separate controller and layout area to load pages for shops outside of the shopify admin. 

This controller will just be a regular rails controller with authentication filters confirming the user is an admin. You'll also need to re-work how you set the API session in the admin controllers since you won't be able to re-do the oauth flow to acquire an access token. Instead you'll need to load it from your database.

Hope that makes sense. I am going to close this issue since its not a problem with ShopifyApp. I'd recommend re-posting on the [Shopify Forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology) to hear what other app developers have done

**Comment by heldopslippers** [comment]
Hi Kevin, 

Thanxs for the good reply. It is indeed not an issue with the ShopifyApp (or Shopify ofcourse). 
Just leaving this here for people looking for a solution: 

I did the following (in your authentication controller): 
```
before_action :login_again_if_different_shop, unless: :is_admin?
around_filter :shopify_session, unless: :is_admin?

def is_admin?
  #Your authentication for deciding if somebody is admin, example:
  session[:admin] == true
end
layout (ShopifyApp.configuration.embedded_app? or is_admin?) ? 'embedded_app' : 'application'
```

**Comment by kevinhughes27** [comment]
Awesome thanks for sharing!
