### ISSUE TITLE
Need help with Deploying shopify app to heroku

### ISSUE THREAD

**Issue by gopinathpara** [Shopify/shopify_app#231]
Hi Kavin,

I've posted this on shopify's partner techenical forum. I though its a good ides to post here as well. Hope that fine.

I've been trying to work on my first app using rails plugin. I followed the instructions as documented by shopify here. Everything is working fine on the first deploy to heroku. I can see the login screen when I opened the huroku app url for the first time. but if a made any changes to any other file, commit those changes and push to heroku master then I'm getting the following errors 

"Precompiling assets failed." which is obversely causing "Push rejected, failed to compile Ruby app".

So to fix this Precompiling error i was advised to add this code line "config.assets.initialize_on_precompile = false" to config/application.rb. so i added it as the last line of code in that file. 

Now when i try to push this changes, i can see the changes are getting deployed to heroku but now the app will not working and display "Application Error".

Any ideas of why this is happening ? any insights to troubleshoot this would be very helpful :)

Thanks for your time!

 

System Specs : OS X El Captian , Ruby 2.2.3p173 , Rails 4.2.6, postgresql

```
Commands that i used to generate the app

$ rails new PopifyNew -d postgresql
$ cd PopifyNew
$ git init
$ git add .
$ git commit -m 'new rails app'

$ heroku create popifynew
$ heroku git:remote -a popifynew

$ open Gemfile — > add  shopify gem —> gem 'shopify_app', '~> 6.0.6'
$ bundle install

rails generate shopify_app -api_key=bd0908ec715d857d3f1808a9a7416e85 -secret=d0ae9fa467683a81c3e6e2a5a43a7a5a -redirect_uri=https://popifyapp.herokuapp.com/auth/shopify/callback

git add .
git commit -m 'generated shopify app'

Change config.redirect_uri to config.redirect_url = "https://popifynew.herokuapp.com/auth/shopify/callback"

git push heroku master
heroku run rake db:migrate
```

**Comment by kevinhughes27** [comment]
This is a heroku issue and is unrelated to Shopify App. I'd recommend using the latest rails and following the heroku guide on how to set up heroku and rails https://devcenter.heroku.com/articles/getting-started-with-rails4. You also may want to add the rails_12_factor gem the heroku recommends.

Also please rotate your api key and secret since you included them in the post above someone could impersonate your application.

**Comment by kevinhughes27** [comment]
I still have heroku precompile my assets for my projects I think that fix is out of date. Are you sure you didn't add anything else to your assets that might be causing them to fail building? Does your app run locally?

**Comment by gopinathpara** [comment]
Hi Kevin,

Thanks for your response. I spoke to heroku and was advised that there is an issue with `redirect_uri `. I also see this error in command line 

`NoMethodError: undefined method `redirect_uri=' for #<ShopifyApp::Configuration:0x007f98d3bcaa98>`

Can you advise if this is some issue with shopify_app gem ?

**Comment by kevinhughes27** [comment]
@gopinathpara looks like you are using an old version of them gem along with new instructions. The current release is 6.4.2. redirect_uri was not a thing in 6.06 which looks like you are using from your code above. 

We're actually going to be removing redirect_uri for v7 though since its not necessary. In your case I would recommend bumping to 6.4.2 and also re-generating your app since the generators have changed.

Quick question - what guide were you following so I can make a note to use the latest version there.

**Comment by gopinathpara** [comment]
@kevinhughes27 Thanks for the response. I was actually following this guide 
https://github.com/Shopify/shopify_app/blob/master/QUICKSTART.md but then i realised the some of the commands and gem referred in the tutorial are not up to date. But mostly the above guide.

Thanks again Kevin. I'll update the Shopify gem version and will redo the app. hopefully, this will solve the issue.

**Comment by kevinhughes27** [comment]
Okay thanks. I'll read through quickstart and make any changes to make this more clear.

**Comment by MassMadankumar** [comment]
config/initializers/shopify_app.rb:5:in `block in <top (required)>': undefined method `redirect_uri=' for #<ShopifyApp::Configuration:0x000055c2ea7efda8> (NoMethodError)
