### ISSUE TITLE
Questions on webhooks

### ISSUE THREAD

**Issue by joshreeves** [Shopify/shopify_app#235]
I have used the API in the past to create webhooks, and when I do, they show up at the `/admin/webhooks.json` API endpoint. I have the auto-created webhooks working with the latest code in this repo, and am receiving the expected webhooks. However, they do not show up at the `/admin/webhooks.json` API end point. Wondering if anyone had any insight on why that might be. Thanks.

**Comment by kevinhughes27** [comment]
The webhooks index page (/admin/webhooks.json or fetching from the api) only shows the webhooks that belong to you. So if you check the admin endpoint it only shows webhooks created in the admin. If you make a request with your api token you will only see webhooks that belong to your app. This way you can't see and interact with webhooks that belong to other people.

Perhaps you were using a private api key to create webhooks in the past which is why they showed up in the admin endpoint.
