### ISSUE TITLE
webhook documentation in the readme file

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#256]
In the readme file it says

"The job will be queued with 2 params shop_domain and webhook which is the webhook body."

In the example code job is created like this

`class CustomWebhooksController < ApplicationController
  include ShopifyApp::WebhookVerification

  def carts_update
    SomeJob.perform_later(shopify_domain: shop_domain)
    head :ok
  end
end`

generator creates a controller for the job like this

`class UninstalledJob < ActiveJob::Base
  def perform(shop_domain:, webhook:)
    shop = Shop.find_by(shopify_domain: shop_domain)
    unless shop.nil?
    shop.destroy
    end
  end`

I added shop destroy, action so my question is, how is webhook params pushed to to this job? It looks like only shopify_domain is sent.

I was trying to capture shop.id parameter out of webhook body but receiving "undefined method" error

`store = webhook

 store_id = webhook.id`

**Comment by kevinhughes27** [comment]
The custom controller example in the readme was a little incomplete (I just updated it). However this only applies if you make your own webhook controller.

If you look at the supplied controller https://github.com/Shopify/shopify_app/blob/master/app/controllers/shopify_app/webhooks_controller.rb#L8 you can see how the webhook is passed into you job.

I don't know the exact contents of that webhook body (it might even be blank). I am pretty sure we don't send the shop_id though since that is not useful to anyone. The webhook does include the shop_domain and thats what you should use to lookup anything related to that shop in your data base.

**Comment by uurcankaya** [comment]
thanks! much appreciated!
