### ISSUE TITLE
Flow for private apps

### ISSUE THREAD

**Issue by rjocoleman** [Shopify/shopify_app#268]
What is the flow please for private apps?

My review of the code is they're not possible with this, using the non-oauth API key and password pair:

```ruby
shop_url = "https://#{API_KEY}:#{PASSWORD}@SHOP_NAME.myshopify.com/admin"
ShopifyAPI::Base.site = shop_url
```

My understanding is the API is the same just different auth methods?

**Comment by kevinhughes27** [comment]
Yes the API is just same just the way you set up the auth is different like you mentioned.

ShopifyApp is mostly for providing all the code around oauth although it has some other helpers now for things like creating webhooks.

The main reason to make a private app is because its easier to setup since it doesn't need oauth. I should note that even if you don't intend to list your app or install it on many shops you can still use oauth  as your auth method which would make it possible to use this gem. I wouldn't recommend this gem if you are going to use a private app.
