### ISSUE TITLE
Embedded app layout has application.js in wrong place to honour data-turbolink-track parameter

### ISSUE THREAD

**Issue by redronin** [Shopify/shopify_app#289]
I noticed that using turbolinks 5 with the embedded_app.html.erb layout file, turbolinks does not honour the data-turbolinks-track=true parameter if the application.js is being loaded outside of the <head> tag.

https://github.com/Shopify/shopify_app/blob/19bc142036376bb1b7881c804af4b4ba8cc4c8a1/lib/generators/shopify_app/install/templates/embedded_app.html.erb#L32

https://github.com/turbolinks/turbolinks#reloading-when-assets-change

This was causing multiple event listeners to be binded. Moving the application.js line into the <head> solved the issue.

**Comment by kevinhughes27** [comment]
Does changing the key to be `data-turbolinks-track="reload"` fix the issue as well?

**Comment by redronin** [comment]
I didn't check.
I just read in the turbolink 5 docs that the link needs to be in the <HEAD>
and just tried that and that fixed my problem.

**Comment by kevinhughes27** [comment]
We could also add a turbolinks permanent attr. @nwtn I think you moved the JS out of the head - thoughts?

**Comment by nwtn** [comment]
Ugh, that's frustrating. If there’s any way to do this without having the script tag in the head, that would be ideal -- having resources like this in the head blocks rendering until the JS is downloaded and executed, which is a performance bottleneck.

@Shopify/channels-fed have any of you run into this? Thoughts?

**Comment by tylerball** [comment]
This would explain a lot.

**Comment by mikeyhew** [comment]
@nwtn let me know if your situation is different, but for most of my apps it's better that the page is kept from rendering until scripts execute anyway, since the app ui is useless without javascript. As a user of web apps, I also find that I get annoyed when I click on a button and nothing happens because javascript is loading. As far as I know, a big problem with scripts in the head is the lower page load time hurts your google search ranking, but for embedded apps that doesn't apply.

I guess there are some cases where you have one widget that is much slower to load than the rest of the UI, like a google map or something, and you don't want it to slow down the rest of the UI. In that case, does the `async` attribute for scripts help?

**Comment by nwtn** [comment]
Since this is apparently not working the way it is now, I definitely think a PR to put the `script` back in the `head` is warranted. Let’s get a fix for the immediate problem. @redronin would you be able to do a PR?

Longer-term I think this is worth taking a closer look at, and I’ll keep it on my radar. @mikeyhew you’re right that a fast first paint with an unusable page is not a good experience, and that’s not what we’d want. Ideally we’d be able to render something useful and usable server-side — e.g. with links instead of JS-dependent buttons, or legible content etc. — and enhance this experience when the JS loads.

`async` (and `defer`) on scripts are also good potential solutions (or partial solutions). If `async` on the `script` tag in the `head` doesn’t cause problems, I think that would be a great compromise for now.
