### ISSUE TITLE
Updating App Scopes

### ISSUE THREAD

**Issue by uurcankaya** [Shopify/shopify_app#324]
It used to automatically redirect user to auth screen when there is a change in app scopes, now it is not doing it and gives 403 forbidden error.

Any ideas?

**Comment by kevinhughes27** [comment]
Can you provide some replication steps? Also is this an issue with Shopify App specifically?

**Comment by uurcankaya** [comment]
- create an app with certain scopes and install it to a store

- change scope of the app and deploy

- go back to store to login 

and you are not redirected to authorization screen to give permission to new scopes

**Comment by kevinhughes27** [comment]
Did you clear the session? If you still have a session it would just use it rather than re-authorizing

**Comment by uurcankaya** [comment]
How do you suggest clearing sessions? Deleting tokens? Isn't still there a chance that user may try to use the app without updating permissions?

**Comment by kevinhughes27** [comment]
What session store are you using? I am trying to narrow down if the issue
is in shopify app or if it is in shopify.

**Comment by kevinhughes27** [comment]
To elaborate if you are using a cookie session store you need to clear you cookies. If you are using redis flush redis etc.

**Comment by ashmaroli** [comment]
I suspect something got changed at Shopify's end. I generated two new apps with same credentials:
- one with shopify_app v7.1.0
- one with v7.0.11 (uninstalled v7.1.0.)

and ran them independently (locally).
Both raised the same error, only, in my case, it was `404 - Not Found`

If you can replicate the same error by following the same steps, we'll be able to debug better.
If you still dont get a 404, I probably didnt generate the apps properly.

**Comment by kevinhughes27** [comment]
@EiNSTeiN- have there been any changes recently?
@alanhill can you try and reproduce?

**Comment by EiNSTeiN-** [comment]
I don't know of anything that could have changed to produce this behavior

**Comment by uurcankaya** [comment]
@kevinhughes27 i am kinda confused, how can i delete all cookies from the app? Consider me a newbie to rails

I tried with session.destroy, but it is probably not the best solution. There should be a easier way to detect app scope change.

If we could pick app scopes from Partner dashboard, that would be the best, then Shopify would detect the change and could force for reauthentication

**Comment by EiNSTeiN-** [comment]
@uurcankaya I don't believe shopify_app offers any facilities to automatically re-authorize the app when you change your configured access scope. I also don't believe it ever did. You may have seen the authorization screen in the past because your session expired (ie. the session cookie stored in your browser had expired) or you used a different browser.

There are two ways I would suggest you can solve this problem, both of which you will need to program on your own:
1) After making a change to your app's scope, expire all cookies in your app to force users to reauthenticate. In the default configuration of shopify_app this means users will see the grant screen again and authorize the new scope. How to expire cookies is totally dependant on how you programmed you app to store them. If you are using Redis, then flush all keys from redis.
2) The other solution is to store the scope you requested in the user's session. Then program your app to disregard the session and reauthorize the app when the scope mismatch.

**Comment by ashmaroli** [comment]
So sorry guys, it was indeed an error at my end.. I revisited the settings in I entered for the new apps, I didnt verify if 'Enable embedded app SDK' was checked.
All is well, And this entire issue is simply a non-issue.. I repeatedly changed the scopes in my test-apps and they were successfully detected by Shopify..

**Comment by kevinhughes27** [comment]
So you had the ESDK un checked but your app was loading the ESDK javascript?

**Comment by ashmaroli** [comment]
The ESDK was checked 'disabled' by default. I overlooked that while generating a new app on Shopify.
I realised the error when I checked the chrome console. The javascript file requested was returning the 404 as `forceRedirect` was set to true in embedded_app.html.erb

**Comment by kevinhughes27** [comment]
ahh okay thanks for the clarification

**Comment by AmitPatel-BoTreeConsulting** [comment]
@EiNSTeiN- what if the app is paid? Does shopify have prorate the billing in such case?

**Comment by Rathnakreeswaran** [comment]
After the installing the shopify public app how it will be reflected in online store website? i am unable to get store front end access token. kindly anyone help me to do further?
