### ISSUE TITLE
Receive Webhooks with localhost:3000

### ISSUE THREAD

**Issue by SylarRuby** [Shopify/shopify_app#336]
Can the webhook address be `http://localhost:3000/webhooks/products_update`? If yes then nothing is working. When I ran the code below, then edited a product in shopify, my console shows nothing after hitting the save button:

```
rails g shopify_app:add_webhook -t products/update -a http://localhost:3000/webhooks/products_update

```

**Comment by kevinhughes27** [comment]
You cannot receive a webhook to localhost since only your computer knows
what the address of your own localhost is. Shopify can't route to your
machine unless you tell it how. I recommend using ngrok or forward to test
webhooks locally.

**Comment by SylarRuby** [comment]
In your youtube video I see you used https://forwardhq.com 😉 Thanks

**Comment by SylarRuby** [comment]
@kevinhughes27 Ive used the link above to get a forward. Link works but still not triggering a product update. Nothing in console when I change a product price. Do I need to do something in shopify? Im now using Rails 5.

**Comment by buggy** [comment]
https://ngrok.com/ works well. Make sure you've modified the webhooks configuration in config/initializers/shopify_app.rb to use the URL that ngrok provides and that you've re-install the app so that it adds the webhooks with the correct address. You can monitor webhook callbacks in the terminal window that you launched ngrok in.

Also, if you re-start ngrok remember that you'll get a different URL so your old webhooks will start failing if the app is still installed.

**Comment by SylarRuby** [comment]
@buggy Ok. One draw back to all this. If I need to add another webhook, the user has to reinstall the app. Tell me there is another way of adding webhooks.

**Comment by kevinhughes27** [comment]
If you need at add another webhook later you can do it in a rake task or
something.
