### ISSUE TITLE
For embedded apps, signing out will show the install page inside of the store's admin panel.

### ISSUE THREAD

**Issue by travishaynes** [Shopify/shopify_app#338]
Perhaps redirect them to their store's apps page instead?

**Comment by kevinhughes27** [comment]
It's because of this code here: https://github.com/Shopify/shopify_app/blob/master/lib/shopify_app/sessions_concern.rb#L36

Maybe logout_url could be a setting. 

Also what is your flow the results in the user logging out? I haven't built this into any of our apps so I am curious what it looks like.

**Comment by travishaynes** [comment]
I agree. Devise implements this well with methods called something like `after_sign_out_path` and `after_sign_in_path` that you can override when necessary. Maybe we could do the same?

I don't actually use this myself, either, except in development, which is how I noticed it. I just thought it was an odd choice to redirect the user to an install page that renders inside of the admin panel after they sign out of an app they already have installed.
