### ISSUE TITLE
Listing our own app webhooks

### ISSUE THREAD

**Issue by vrehm** [Shopify/shopify_app#414]
Hello,

We've got a ruby on rails app connected to our shop courtcircuit.myshopify.com.
We use the shopify_app gem and we've got this concern :

How can we get a list of our webhooks created with the shopify_app gem and their statuses, as this API call (https://courtcircuit.myshopify.com/admin/webhooks.json) return only ones created in the shopify admin, not by the shopify_app

Thanks.
Greetings

Vincent

**Comment by diegolearnstocode** [comment]
Would love to know this as well!

**Comment by charlesemarsh** [comment]
I don't think there will be a way of getting all webhooks, since you have to call each store to get the webhook data. 

I just use ShopifyAPI::Webhook.all when I have an active store session

**Comment by vrehm** [comment]
thanks @charlesemarsh, we were looking for that, it's not listed in the documentation \o/

**Comment by jamiemtdwyer** [comment]
The API will return a list of webhooks created by your application, given the correct credentials.

If you are seeing webhooks created from the shop admin, this is because you are logged in as a shop administrator rather than using the API credentials.

In the future, it's preferable to have these issues created [here](https://github.com/shopify/shopify_api/issues).
