### ISSUE TITLE
Testing controllers that inherit from ShopifyApp::AuthenticatedController

### ISSUE THREAD

**Issue by ahogerland** [Shopify/shopify_app#445]
_This was initially posted on the [Shopify forums](https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/testing-controllers-in-a-rails-5-app-using-shopify_app-gem-454769), but was recommended to post it here._

I am using Minitest for testing. My controllers inherit from `ShopifyApp::AuthenticatedController`, and so in order to test them I need to somehow stub/mock a Shopify session. Previously with `ActionController::TestCase` there was a simple solution to this: 
```
@request.session[:shopify] = shop.id
@request.session[:shopify_domain] = shop.shopify_domain
```
But with [the move](https://github.com/rails/rails/issues/22496) to `ActionDispatch::IntegrationTest`, there is no longer any access to the `@request` instance variable when testing controllers.

What are the best practices for testing controllers that inherit from `ShopifyApp::AuthenticatedController` in Rails 5?

**Comment by kevinhughes27** [comment]
Great question. In Rails 5 Integration Tests are just as fast as controller tests but cover more area so controller tests were removed. This does mean that some kinds of mocking like you described don't work anymore. The solution is fairly intuitive but easy to miss if you're used to controller tests.

Every test starts by calling a helper which follows the authentication flow which internally sets the session for you. Then make the desired second request to test in your test.

```ruby
def login_to_shopify
  get '/auth/shopify'
  follow_redirect!
  # session is available now. You could look up the Shop model here and return it if you want
end
```

Of course this isn't enough since this request gets directed to a 3rd party. This is where Omniauth test mode comes in:

```ruby
OmniAuth.config.test_mode = true
OmniAuth.config.mock_auth[:shopify] = # shop object
```

**Comment by Ninigi** [comment]
@kevinhughes27 could you elaborate on this line?

```ruby
OmniAuth.config.mock_auth[:shopify] = # shop object
```

I am guessing this has to be an `OmniAuth::AuthHash` but I am having a hard time filling in the blanks here.
Thanks in advance 🙇

**Comment by kevinhughes27** [comment]
That looks correct to me!

Also I've always wanted to include some test helpers in this gem if you want to PR it :)

**Comment by Ninigi** [comment]
@kevinhughes27 the biggest problem is, that you need to trigger the authorization differently depending on the usecase... For example in a capybara test, you would need to do `visit "/auth/shopify"`. Not even talking about other frameworks here :(
Not impossible to solve, but I just don't have the time right now.

**Comment by kevinhughes27** [comment]
Fair enough! I've run into that as well and I'm not sure the cleanest way to solve it either.

**Comment by waseem** [comment]
@Ninigi How did you get that working? I face an error when trying to do above.

So I have

```ruby
# spec/controllers/admin/dashboards_controller_spec.rb

require 'rails_helper'
RSpec.describe Admin::DashboardsController, type: :controller do
  fixtures :shops

  describe "#show" do
    let!(:shop) { shops(:a_shop) }
    before do
      login(shop)
    end

    it "passes" do
      expect(true).to be
    end
  end
end
```

```ruby
# spec/support/admin_controller_test_helpers.rb

module AdminControllerTestHelpers
  def login(shop)
    OmniAuth.config.test_mode = true
    OmniAuth.config.add_mock(:shopify, uid: shop.shopify_domain, credentials: { token: shop.shopify_token })
    Rails.application.env_config["omniauth.auth"] = OmniAuth.config.mock_auth[:shopify]

    get "/auth/shopify"
  end
end
```

And the error is:

```
1) Admin::DashboardsController#show passes
     Failure/Error: get "/auth/shopify"
     
     ActionController::UrlGenerationError:
       No route matches {:action=>"/auth/shopify", :controller=>"admin/dashboards"}
```
This has something to do with how rspec works. It assumes `/auth/shopify` to be an action in the `DashboardsController` rather than querying out the URL as it is.

**Comment by Ninigi** [comment]
@waseem It is 1:30 AM for me right now and I really do not recall this issue very well, so please forgive me for giving spongy advice... It looks like you are trying to execute the login at a time, where not all the necessary data is available, as in the method I described heavily relies on an rspec controller/request context.
I don't know what the problem is, but my gut says require the helper file in your TEST file instead of the rspec_helper.
If that is not the problem, the error message indicates that something is wrong with how your shopify gem is set up, because it should provide the `auth/shopify` route.
If that does not help, please open another issue with a reference to this one and a detailed description of your configuration files. Maybe the shopify guys can help you out :fire_engine:

**Comment by m20io** [comment]
I ran into same issues, with not matching route. I suspect rspec only setting up the controller under test routes. Has anyone a working example that could be posted?

**Comment by richardmonette** [comment]
```ruby
require 'test_helper'

class AssetsControllerTest < ActionDispatch::IntegrationTest
  def login(shop)
    OmniAuth.config.test_mode = true
    OmniAuth.config.add_mock(
      :shopify,
      provider: 'shopify',
      uid: shop.shopify_domain,
      credentials: { token: shop.shopify_token }
    )

    get "/auth/shopify"
    follow_redirect!

    ShopifyAPI::Shop.stubs(:current).returns(shop)
  end

  setup do
    login(shops(:regular_shop))
  end

  test "associate should return the corresponding asset if it exists" do
    assert_no_difference('Asset.count') do
      get assets_associate_url
    end

    assert_response :ok
  end
end
```
