### ISSUE TITLE
Please add a more detailed tutorial

### ISSUE THREAD

**Issue by TheLearningTree** [Shopify/shopify_app#469]
Thank you so much for this excellent repo but as a beginner, I have no idea where to start. I've learned RoR and I git cloned this repo and I have no idea what
- channels
- concerns 
- jobs
- mailers

folders are supposed to be, I have no idea what most of these files are as I've just made a simple CRUD in RoR. I apologize if I sound nooby. I would absolutely love a more detailed explanation and usage instructions for this repo. Perhaps adding to the Wiki could be a good idea? 

I know the readme already includes a lot of code snippets, but I don't *where* to start building my logic or even where to add for example the following:

```ShopifyApp.configure do |config|
  config.scripttags = [
    {event:'onload', src: 'https://my-shopifyapp.herokuapp.com/fancy.js'}
  ]
end
```

Are you aware of some good learning resources to help beginners get up to speed quicker? It would be extremely helpful for beginners such as myself :) 

Thank you!

**Comment by kevinhughes27** [comment]
Most of the things you mentioned are from Rails itself and not this gem specifically. I would recommend spending some time learning more about Rails and completing some rails tutorials. 

The specific code you have linked to is part of configuring ShopifyApp. In Rails we typically do this in an initializer file because Rails will run each of this when it starts up. Technically you could write this code anywhere in your app as long as it gets called before any web requests hit a route that uses ShopifyApp.

I am going to close this issue since I don't feel like its particularly actionable for us. I always welcome updates to the documentation and readme if you have something specific to this project to add.
