### ISSUE TITLE
Intermittent ActiveResource::ForbiddenAccess error from ShopifyAPI::Shop.current

### ISSUE THREAD

**Issue by amitpatelx** [Shopify/shopify_app#508]
We have sent an [app](http://apps.shopify.com/ad-champion)(not listed yet) for review to Shopify. The reviewer is getting the mentioned error on `index` action of `HomeController` which triggers when user clicks on install button.  

We verified the app with many development stores in different partners accounts and few live stores as well. We were able to install the app successfully for all the stores we tested.

Here is simplified version of the code 

**controllers/shopify/home_controller.rb**
```ruby
module Shopify
  class HomeController < ShopifyApp::AuthenticatedController
    def index
      MyCustomServie.new(shopify_detail).call
    end

    private

    def current_shopify_store
      @current_shop ||= begin
        with_rate_limit_protection do
          ShopifyAPI::Shop.current
        end
      end
    end

    def shopify_detail
      @shopify_detail ||= ShopifyDetail.find_by(shopify_domain: current_shopify_store.try(:myshopify_domain))
    end

    def with_rate_limit_protection
      yield
    rescue ActiveResource::ClientError => e
      if /Too Many Requests/i =~ e.message   # Hit the API rate limit
        sleep 1
        retry
      else
        raise
      end
    end
  end
end
```

**config/initializers/omniauth.rb**

```ruby
Rails.application.config.middleware.use OmniAuth::Builder do
  provider :shopify,
    ShopifyApp.configuration.api_key,
    ShopifyApp.configuration.secret,
    scope: ShopifyApp.configuration.scope,
    callback_path: "#{Settings.shopify.mounted_at}/auth/shopify/callback"

  provider :google_oauth2,
           Settings.google.client_id,
           Settings.google.client_secret,
          { access_type: "offline", approval_prompt: "" }
end

```

**conffig/initializers/shopify_app.rb**

```ruby
ShopifyApp.configure do |config|
  config.application_name = 'Shopify - Feed Champion'
  config.api_key = Settings.shopify.api_key
  config.secret = Settings.shopify.api_secret
  config.scope = Settings.shopify.scope
  config.embedded_app = true
  config.after_authenticate_job = { job: ShopifyAfterAuthenticateJob, inline: true }
  config.webhooks = [  Shopify::AppUninstalledWebhook::PARAMS  ]
end
```

The [error](https://www.dropbox.com/s/1u1g92qponexd93/forbidden_shopify.log?dl=0) comes from the below line `ShopifyAPI::Shop.current`.

**Comment by kevinhughes27** [comment]
What Shop repository do you have configured? I don't see anything setup. If you are using the InMemoryStore this would explain the results as each server would have a different store.

**Comment by AmitPatel-BoTreeConsulting** [comment]
@kevinhughes27 we have been using ActiveRecord for shop repository

**config/initializers/shopify_session_repository.rb**
```ruby
if Rails.configuration.cache_classes
  ShopifyApp::SessionRepository.storage = ShopifyDetail
else
  reloader = defined?(ActiveSupport::Reloader) ? ActiveSupport::Reloader : ActionDispatch::Reloader

  reloader.to_prepare do
    ShopifyApp::SessionRepository.storage = ShopifyDetail
  end
end

```

**Comment by kevinhughes27** [comment]
Can you rescue the forbidden and check the contents of the shop object?

**Comment by AmitPatel-BoTreeConsulting** [comment]
@kevinhughes27 but we get the error on `ShopifyAPI::Shop.current`. That supposed to return shop object, right?

**Comment by kevinhughes27** [comment]
Oh true. Lets check the current api session object then and see what is in there

**Comment by AmitPatel-BoTreeConsulting** [comment]
I am able to reproduce the issue finally. Here are the steps

1. Install the app
2. Approve the Charge
3. Go back to Apps and uninstall the app
4. Immediately rush to install the app(ps. we have uninstall webhook which gets called later)

This gives `ActiveResource::ForbiddenAccess` error which then redirects to the main app's root. With above steps investigating following method, I am getting `session.delete(:return_to)` as nil and so it takes me to root of my rails app and not the root of embedded app which is `/shopify-app`. The QA guy from shopify doesn't expected this page.

```
def return_address
  session.delete(:return_to) || main_app.root_url
end
```
Now if I wait for webhook to run and then install the app, it works fine.

I try handling those exception by adding following lines in the controller mentioned in the first post above and redirect to a page having error message.

```
rescue_from ActiveResource::ForbiddenAccess, ActiveResource::UnauthorizedAccess do |exception|
  redirect_to shopify_auth_failure_url
end
```
But it shows following page after performing install/uninstall steps mentioned above even if the app return 200 OK.

![selection_999 031](https://user-images.githubusercontent.com/1289894/37342828-c3a74346-26eb-11e8-901a-020de67079e7.png)

Now the question is, 
1. Is this an expected behaviour as per the lines in `return_address`?
2. If yes, then what is best practice as per Shopify's standard to handle such errors?

**Comment by vfonic** [comment]
I'm also seeing similar issue in the same scenario. My app just redirects to embedded app url like in your last screenshot (as it's still authenticated, before the uninstall hook notification arrives).

One possible solution would be to issue extra request (like you do to `ShopifyAPI::Shop.current` and, if we receive `ActiveResource::ForbiddenAccess`, try to re-authenticate user/shop.
