### ISSUE TITLE
Documentation of shopify_api and shopify_app.

### ISSUE THREAD

**Issue by rwojnarowski** [Shopify/shopify_app#509]
I've got question about difference between this two gems. I know that **shopify_app** also include **shopify_api** as dependency. But i cannot understand what is exact purpose of **shopify_app**.
I want to create app in rails with **shopify_app**, i want to allow users to log in/out, create accounts and checkout products and also allow payments. I want to hold all the data on shopify.com. Rails will mostly provide views for end user. 

Is this the right purpose of this gem ? Or should i use **shopify_api** gem? With **shopify_api** i don't have any problem with shop session, i only care for users and their session. Is **shopify_app** only purpose is to create embedded app for shops ?

Similar question on shopify forum:
https://ecommerce.shopify.com/c/shopify-apis-and-technology/t/shopify_api-vs-shopify_app-for-rails-site-300743

**Comment by kevinhughes27** [comment]
`shopify_api` is a library for making API requests to Shopify when provided with a valid session. It provides a few methods that can be used to perform and OAuth handshake manually although I would recommend against it.

`shopify_app` is a Rails engine that provides multi-tenant authentication using omniauth. It handles a lot of logic that you would otherwise need to write on your own. ShopifyApp handles authentication for you and shopify_api is still how you will make API requests. For your use case I would recommend to use ShopifyApp.
