### ISSUE TITLE
Warn people that this gem is changing the locale in the background

### ISSUE THREAD

**Issue by yogodoshi** [Shopify/shopify_app#635]
It took me many hours of debugging and generating hypothesis of why some of my app users were seeing a translation missing error if nowhere in my app I was setting any other locale than the default.

Until I finally discovered that shopify appends the locale param based on the user's config in each request and then I discovered that this gem uses it [here](https://github.com/Shopify/shopify_app/blob/48faaf9e9455ccf467f153765fef077d5062a6e8/lib/shopify_app/controller_concerns/localization.rb), something that is nowhere in the README.

Changing a config as important as the locale automatically by default, shouldn't it at least be written in the README?

**Comment by EiNSTeiN-** [comment]
Thanks for the heads up @yogodoshi, I'll add @christianblais to this issue for advice as to how to handle this in third party apps.

**Comment by edavis10** [comment]
I think this is more than a docs issue.

I'm seeing the locale leaking to other threads. I've been seeing non-default languages in my admin panel for months that have come from stores in other sessions having their locale and I18n set.

Per the Rails docs:

> I18n.locale can leak into subsequent requests served by the same thread/process if it is not consistently set in every controller. For example executing I18n.locale = :es in one POST requests will have effects for all later requests to controllers that don't set the locale, but only in that particular thread/process. For that reason, instead of I18n.locale = you can use I18n.with_locale which does not have this leak issue.

https://guides.rubyonrails.org/i18n.html#managing-the-locale-across-requests

The Localization module is only included in Authenticated so it's missing in the non-authenticated controllers and any non-shopify_app controllers (e.g. admin control panels).

Rails recommends using `I18n.with_locale` along with an `around_action` instead of the `I18n.locale` with a `before_action` that Localization uses.

I decided to patch `set_locale` to make it a no-op since I don't use localizations and am not able to supply a PR to the gem itself.

Rails 6.0.2.1
shopify_app 12.0.2
Puma 4.3.1
