### ISSUE TITLE
No authentication prompt on updating the app scope.

### ISSUE THREAD

**Issue by HulkApps** [Shopify/shopify_app#683]
Hello everyone,

We are trying to update our application scope but, we aren't getting an authentication prompt after updating the app scope on the server. Any suggestions/solutions ?

As per my knowledge, whenever we update our application scope, our users will get an authentication prompt to reinstall/update the application on their store's end.

**Comment by nwtn** [comment]
You’re right, users should be prompted to update and approve the new scopes. After updating the app, did you/the user open it in the store admin? If so, was the user able to open the app and interact with it without approving the new scopes?

**Comment by ragalie** [comment]
What's probably happening is that the user's session is still valid in your app, so your app isn't sending the user over to Shopify to reauthenticate.

If you need everyone to reauthenticate (in order to get the new scope approved), then I think one simple way to do that would be to expire your Rails cookies by changing the `secret_key_base` in your credentials.yml: https://guides.rubyonrails.org/security.html#encrypted-session-storage

We should probably document the process for this though, I haven't personally tried what I just suggested. You should test it out before you try it out on your users.

**Comment by HulkApps** [comment]
@ragalie ,

Thank you for the solution that you provided. It works.!!

**Comment by smathieu** [comment]
I think it would good if this gem kept tracked of requested and approved scopes. Similar to what doorkeeper does. https://github.com/doorkeeper-gem/doorkeeper/blob/master/spec/dummy/db/schema.rb

This would allow apps to avoid API requests that would fail and also add a before_filter to controller to request new scopes if some are missing.

**Comment by skillmatic-co** [comment]
I'm also experiencing this, @ragalie/@bhava-hulkapps can you explain in more detail what you did to get it to prompt for the new scope approval?

**Comment by skillmatic-co** [comment]
Also seems this information is out of date: https://github.com/Shopify/shopify_app/blob/master/docs/shopify_app/handling-access-scopes-changes.md

Doing either/both of those things creates errors.

**Comment by skillmatic-co** [comment]
Bumping this, having this issue again. When I add the line: `include ShopifyApp::ShopAccessScopesVerification` to my HomeController, I get redirected to this Shopify Error page:

<img width="625" alt="image" src="https://github.com/Shopify/shopify_app/assets/144985/8e98858c-fb9c-4f5f-8dc1-55dde4df5ad8">
