### ISSUE TITLE
Blank page and javascript error when loading app on iOS

### ISSUE THREAD

**Issue by jgodson** [Shopify/shopify_app#701]
When loading an app using version 8.5.1 of them gem, on iOS 12.1.4, I got a blank screen. I checked with the debugger and it turned out to be a javascript error

![alt](https://screenshot.click/07-04-bd6sc-5xau7.jpg)

A few other people on my team did get the same problem. One solved it just by hitting the back button, then it seemed to redirect/auth properly. Three of us went to our login page and hit the install button again which seemed to refresh our sessions and correct the error (stale cookies maybe?).

I would expect that this wouldn't need to be done normally in this case and re-auth (or whatever the problem was here) should happen automatically?

**Comment by nwtn** [comment]
I’m going to keep looking into this, but at first glance it looks like this is probably happening because we’re [instantiating a new `StorageAccessHelper`](https://github.com/Shopify/shopify_app/blob/master/app/assets/javascripts/shopify_app/partition_cookies.js#L3) without [passing in `redirectData`](https://github.com/Shopify/shopify_app/blob/master/app/assets/javascripts/shopify_app/partition_cookies.js#L3), which means [we’re trying to access `hasStorageAccessUrl` on `undefined`](https://github.com/Shopify/shopify_app/blob/master/app/assets/javascripts/shopify_app/partition_cookies.js#L3).

@ragalie @francinen does this seem right to you? Do you know if there’s a good reason why we wouldn’t pass in the `redirectData` in `partition_cookies.js`?
