### ISSUE TITLE
App wants to embed even though config.embedded_app = false

### ISSUE THREAD

**Issue by Siggs2000** [Shopify/shopify_app#710]
I'm running version 8.4.2 and rails 5.2.2

I have `config.embedded_app = false` in my shopify_app initializer file but the root view keeps loading in an iframe in the store admin. 

Any tips on this?

**Comment by nwtn** [comment]
To let Shopify know that your app should (or in this case, shouldn’t) be embedded, you need to configure the `Embedded app` app extension in the Partner dashboard. See https://help.shopify.com/en/api/embedded-apps/app-bridge/getting-started#embed-your-app-in-the-shopify-admin for more details. Based on this setting, Shopify will know whether or not to load your app in an iframe in the admin.

`config.embedded_app` lets the shopify_app gem know whether your app is embedded or not, in order to change some app-side (not Shopify-side) behaviour.

**Comment by Siggs2000** [comment]
Thanks @nwtn that was indeed the issue. Thank you!
