### ISSUE TITLE
Webhook Behaviour Question

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#815]
The idea behind the App is that when a webhook is received, the App sends it off to an ActiveJob for processing later, and immediately returns a 200 OK status to Shopify, so Shopify should not send that webhook payload again. Simple. 

I am seeing different behaviour. My job is running, and in my job code, I have some errors. So what, that is my problem. Why is Shopify still sending that order as if it never got the 200 OK status?

**Comment by resistorsoftware** [comment]
never mind... ActiveJob had a retry stuck on it that needed changing

**Comment by tanema** [comment]
Shopify has an at-least-once guarantee so that means there is a possibility of receiving a webhook more than once, however if it is returning more than that then it seems like Shopify is not interpreting your response as successful. This could mean status or a timeout.

Your webhook response should look simething like 

```
  def action
    WebhooksJob.perform_later(params)
    head(:ok)
  end
```
