### ISSUE TITLE
Upgrading shopify_app from 11.1.0 to 11.6.0 is corrupting session

### ISSUE THREAD

**Issue by knagode** [Shopify/shopify_app#911]
When trying to upgrade gem I noticed that Rails' session stopped working for other part of the app if visited trough localhost:3000 (or in test environment). 

Everything works via ngrok but it is annoying because e.g. ActiveAdmin doesn't work anymore on localhost:3000. 

I used initialiser to fix session_store on localhost:3000 and test env:

```
Rails.application.config.session_store :cookie_store, key: '_session', same_site: :strict
```
However this breaks the app on production or when using ngrok. 

Any idea how to approach this problem properly?

**Comment by tanema** [comment]
Yes, you now need to always use a tunnel. Because of the SameSite policy required by Chrome, the app needs to be served over https so that we can add the secure attribute to cookies. The secure attribute is required when setting SameSite=none.  The session is not corrupt, it will just not set the cookie because you are serving over http but the secure attribute is on the cookie. When you set same_site: :strict, you are overriding our middleware so that is why it fixes it but then it will not work in production for your users with updated Chrome

**Comment by knagode** [comment]
I did that because my rspec feature tests started failing (any tests which were using session somehow - apparently because test environment doesn't use SSL)
Also because e.g. ActiveAdmin stopped working if visited via localhost:3000. 

It seems like adding `secure` attribute to cookies should only happen if request is using SSL. Otherwise it is affecting parts of the app which are irrelevant to Shopify. That way we could use the app on both http://localhost:3000 (parts which are not relevant to shopify) and https://xyz.ngrok.io. Or is there a better solution for this?

**Comment by knagode** [comment]
https://github.com/Shopify/shopify_app/pull/912

I played with it and it seems like this would spare many headaches :)
