### ISSUE TITLE
Custom Carrier Verification

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#926]
When we create an endpoint to receive checkout payloads for inspection, to generate shipping rates, we get the same HMAC security as a webhook. So in my controller I can just include the WebhookVerification module and carry on my merry way. 

It does seem weird though. Maybe there is a better way? I would not want to dupe the module and give it a name for Custom Carrier as that is not DRY. So since this verification happens the same for custom carrier payloads and webhooks, possibly app proxy, is there a plan to perhaps abstract this to just being "verification", and then it is clear what to include when needed?

**Comment by tanema** [comment]
Yeah you are right, I thought this work was done when the extension verification was added because that also duplicates this same code. We should just refactor this into a shopify payload verification module. I *do* like having modules that indicate what they are for so even if I do this refactor, I would still have a WebhookVerification and a CustomCarrier module just in case their functionality diverges and because then it makes more sense to newer developers.

**Comment by resistorsoftware** [comment]
I love the use of that word Payload. As for tagging it with some sense of where it comes from, I am sure there is a way to include the verification code as a low-level module, perhaps inside a module tagged with the specifics, hence not really ruining the nice DRY experience other devs might crave.

**Comment by adfaris** [comment]
@tanema 

I will get started extracting into payload_verifcation_module
