### ISSUE TITLE
Connecting a second shop in same browser session disconnect the first one - embedded app

### ISSUE THREAD

**Issue by damienlethiec** [Shopify/shopify_app#941]
Hi there,

I am working a Shopify App which work great in development. In production, I made it an embedded app.

The app works perfectly when installed in 1 shop. It also works perfectly if I open a new private session in my browser when 1 work on a second shop. However, when I try to access or connect my second shop in the same browser session, the first shop gets "disconnected".
I get an "undefined method root_path" error (I tried to change the route but same issue)

The URL when I get the error is : https://shopify-magistor-connector.herokuapp.com/top_level_interaction?shop=relics-clothing.myshopify.com

Normally, when everything works fine, the URL is :https://relics-clothing.myshopify.com/admin/apps/c37b09b569e112e29221660960d67490/?hmac=436383078c7a7611837b319de5b65b9eb0a746c640c660c65ba9b721810d1034&locale=fr-BE&session=3ad0cc663d0a82206b419dcee0f919a2f135d2b330ecc72b49e8ac94ebe01ce4&shop=relics-clothing.myshopify.com&timestamp=1585642373

Do you understand why? Could you help me with this?

Thanks

**Comment by marschattha** [comment]
True this happens.
I assume the cookie token for authentication is overwritten on login from the seconds shop.

**Comment by tanema** [comment]
Yes, it is likely because your cookie store is overwriting the session in your browser for your domain. Generally, most application configuration expects that you only have one session for your browser for each application. You are trying to have 2 different sessions for a single application in your browser. This *is* possible to do but quite tricky to pull off.
