### ISSUE TITLE
Weird message inside Session

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/shopify_app#949]
Shopify App 13.0.0
Shopify API 9.0.4

Scenario. Inside a valid Shopify API session setup inside an ActiveJob as per this code:

    shop.with_shopify_session do
      query = Queries::GetShopName.query
      response = ShopifyAPI::GraphQL.client.query(query)
      puts "response: #{response.data.shop.name}"
    end

This works, in that the response from GraphQL request is correct. But I am seeing this warning and I am curious as to why. I thought Shopify App takes care of that initialization.

**[WARNING] Client was not pre-initialized. Ensure `ShopifyAPI::GraphQL.initialize_clients` is called during app initialization.**

**Comment by tanema** [comment]
It takes care of that initialization but it seems like you should be calling `ShopifyAPI::GraphQL.initialize_clients` as part of your initialization so that it has a cached client that you can be sure is ready and valid for you app to use. In this case, it will create that client on the fly which may not be safe.

**Comment by resistorsoftware** [comment]
I am not understanding. If I should be calling that initialize_clients method, it means the main Rails App is not, for Jobs anyway... But if I do insert a call to that method, it may be unsafe?
